services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: interview
    ports:
     # - "5432:5432"
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./apps/api
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - ./apps/api/.env
    environment:
      - OPENAI_TTS_VOICE=${OPENAI_TTS_VOICE:-coral}
    volumes:
      - ./apps/api:/app
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  web:
    build:
      context: ./apps/web
    command: npm run dev
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_INTERVIEW_STREAMING=true
      - NEXT_PUBLIC_INTERVIEW_REALTIME=false
      - NEXT_PUBLIC_OPENAI_REALTIME_URL=https://api.openai.com/v1/realtime
      - NEXT_PUBLIC_OPENAI_REALTIME_MODEL=gpt-4o-realtime-preview
    volumes:
      - ./apps/web:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - api
    ports:
      - "3000:3000"

volumes:
  postgres_data: 